### ISSUE TITLE
Enhancement: Shorten long hotkey text on action buttons

### ISSUE THREAD

**Issue by gashole** [obble/modui#102]
There are many hotkeys that do not display properly on action buttons because of their length, e.g., "Mouse Button 5" is "Mo...". These need to be shortened.

![before](http://i.imgur.com/aWL8iGg.png) vs ![after](http://i.imgur.com/gRwzKpQ.png)

https://github.com/gashole/modui/commit/b04c39a1de978e12215d8ddcd49e6595742f338b

**Comment by obble** [comment]
added to next revision
