### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kefirok** [obble/modui#103]
- Copy class colour in chat function from pfUI
- Add class colour to "Who" and "Guild" windows for **class name**; add class colour for **player name** to "/who" in chat http://imgur.com/VaewCBR
- Add right-click to "M" for open keyring
-  http://imgur.com/ABrDsv9 remove the text selection from item name, after use auto-search(looks ugly); add "Reset" button like on retail
- delete this function(map) cause work bad http://imgur.com/s8JMKFH
- move all text to localization files; if some text not translated, use default locale for this text (i'll try translate to russian, but not promise)

**Comment by obble** [comment]
what's wrong with the coordinates? they work fine.

class colours on chat messages is a function that i have conspicuously avoided in the past and will continue to do so ~ pfUI and other addons essentially build a huge table of player names by storing them through interactions, mousing over other players, group-sharing, etc. etc. and it's often both patchy and bottomless; with the player densities on elysium that table will get very big very quickly.

i have added class colours to friends list, who searches & guild rosters for the next revision though.

an incomplete version of the localisation files exists, but i'm considering dropping it unless proper support turns up in the next little while ~ and primarily supporting english clients.

**Comment by obble** [comment]
some of these suggestions have been integrated into v86.

**Comment by kefirok** [comment]
Not coordinates. Online on map work bad.

**Comment by kefirok** [comment]
Bad news about localization :(
