### ISSUE TITLE
Enhancement: Turn action buttons red when out of range

### ISSUE THREAD

**Issue by gashole** [obble/modui#104]
The hotkey text turns red when out of range, but this is hardly noticeable.

![before](http://i.imgur.com/28IGuJZ.png) vs ![after](http://i.imgur.com/r7yqmPB.png)

https://github.com/gashole/modui/commit/b98e676342c82f7a9e49f52d83408100c6ff961a

**Comment by kefirok** [comment]
Maybe turn dark looks better? Like on retail

**Comment by obble** [comment]
yeah i've added this to the next revision but changed it so that the icons darken rather than redden the icon ~ i've also added the blue tone that retail uses to indicate spells that cost more mana than the player currently has, via the second return from IsUsableAction(id)
