### ISSUE TITLE
Enhancement: Hide energy timer while resting/mounted

### ISSUE THREAD

**Issue by AmplusNLD** [obble/modui#105]
I think it is a nice touch to hide the energy timer when you don't need it. So you don't see your bar blinking all the time.

**Comment by obble** [comment]
this was how the bar was originally designed, but most rogues asked for it to be enabled all the time because it dictates how and when they choose to enter combat.

**Comment by obble** [comment]
as you say, it could be reintroduced in "resting" scenarios, but i think even on a mount there would be points where certain users would say they are inconvenienced by it disappearing.

**Comment by AmplusNLD** [comment]
Okay, you got a point, I didn't know it was originally designed like that. 
Maybe give it a softer look, instead of hiding it completely.

**Comment by obble** [comment]
yeah maybe i could knock the opacity down a notch whilst out of combat

**Comment by obble** [comment]
>> [86.5](https://github.com/obble/modui/commit/0a90edcbdaa285481ad31f5b4581e00edcf94e28)
