### ISSUE TITLE
86

### ISSUE THREAD

**Issue by kefirok** [obble/modui#106]
- New bugs http://imgur.com/vYcsDx9  and http://imgur.com/MFchKOa
- Please make a smooth cooldown count(sharp counting animation). Sometimes cooldown not work http://imgur.com/u2RntZc

+ Add class-coloured **PLAYER NAME** for this http://imgur.com/VaewCBR
+ Make class-coloured **CLASS NAME** not player name for friends, who, guild panes (like retail)

Thanks for good work.

**Comment by kefirok** [comment]
+ new bug http://imgur.com/vYcsDx9

**Comment by kefirok** [comment]
Please make a smooth cooldonwn count.

**Comment by obble** [comment]
>> [86.5](https://github.com/obble/modui/commit/0a90edcbdaa285481ad31f5b4581e00edcf94e28)

I won't currently be adding class colours for /who searches that return into the chatframe.

**Comment by kefirok** [comment]
Keyring fixed?
