### ISSUE TITLE
Cooldown timer not showing every time on low cd spells

### ISSUE THREAD

**Issue by johnnybgood89** [obble/modui#111]
Cooldown timer not showing every time on low cd spells

**Comment by obble** [comment]
are you using the latest version (currently: 88)? i noticed this today and made a change in the code (away from OnUpdateModel and back to an OnUpdate for the cooldown swirl frame) that seemed to fix this issue for me.

**Comment by obble** [comment]
cc: @gashole

**Comment by gashole** [comment]
I can't replicate this. If it is still a problem in v.88, try changing https://github.com/obble/modui/blob/master/actionbar/cooldown.lua#L26 to 
`if start > 0 and duration > 1.5 then`
***
Edit: Also, try removing these lines
https://github.com/obble/modui/blob/master/actionbar/cooldown.lua#L17
https://github.com/obble/modui/blob/master/actionbar/cooldown.lua#L18

**Comment by johnnybgood89** [comment]
No I didnt use v88, thanks. 

Also @gashole, can you make transition of the numbers when counting little smoother, like in OmniCC?

**Comment by obble** [comment]
that should be the case with the latest version (88), it ticks along a lot more smoothly with OnUpdate.

i'll take a look at those adjustments gashole.

**Comment by gashole** [comment]
@obble it looks like this issue was fixed in v.86.5 and can be closed.

**Comment by obble** [comment]
yeah, thanks!
