### ISSUE TITLE
Player/Target unitframes: Slightly different class color on player/target frame

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#120]
Slightly different class color on player/target frame
![image](https://cloud.githubusercontent.com/assets/6162744/22510227/72f6f854-e891-11e6-93ce-ebd3958f7f07.png)

**Comment by AmplusNLD** [comment]
Are you sure it's modui? Maybe it's some other addons that skins it as well. My bars look completely fine, even checked it with color picker.

![2017-02-01 16 24 40](https://cloud.githubusercontent.com/assets/25012428/22512990/1290e1fa-e89b-11e6-82ae-9ecb95274800.jpg)

**Comment by Steffen-Hadberg-Nielsen** [comment]
Hmm you're right. I just disabled all addons but modUI and it looks fine now - i'll report back when I find out which addon makes it happen

**Comment by Steffen-Hadberg-Nielsen** [comment]
Apparently it was [SuperInspect](http://addons.us.to/addon/superinspect-0) which caused this, not sure why though 😕

**Comment by AmplusNLD** [comment]
Well at least you found the cause…
