### ISSUE TITLE
Raid Frames: Option to set height/width of the raid member frames

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#122]
Option to set height/width of the raid member frames

**Comment by obble** [comment]
as of version 91:

![size2](https://cloud.githubusercontent.com/assets/96432/22572671/17415376-e99d-11e6-9e58-9ea6acbeada3.gif)

greater fidelity in terms of resizing, arranging and positioning will come as options are fleshed out.
