### ISSUE TITLE
Error after latest commit

### ISSUE THREAD

**Issue by kev41** [obble/modui#125]
Getting this error everytime I cast mount/seals atm.

![errorrr](https://cloud.githubusercontent.com/assets/21115526/22556632/28ef56a2-e968-11e6-9aa4-46a5761bb353.jpg)

**Comment by obble** [comment]
this should be fixed in v91

**Comment by kev41** [comment]
Still have this on latest commit

**Comment by kev41** [comment]
but it says Count: infinite instead of 2
