### ISSUE TITLE
Smooth.lua line 68 error

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#134]
This error is getting spammed in the chat like crazy
![image](https://cloud.githubusercontent.com/assets/6162744/22647273/c92e991a-ec70-11e6-8606-ae188c42d5d1.png)

**Comment by obble** [comment]
ah, do you have custom nameplates off by any chance?

let me know if [v98](https://github.com/obble/modui/commit/d1d0563f9de8ae48dbfd31be498c472da9c985ef) fixes your woes.

**Comment by Steffen-Hadberg-Nielsen** [comment]
Yeah I'm using pfUI's nameplates :)

https://github.com/obble/modui/commit/d1d0563f9de8ae48dbfd31be498c472da9c985ef fixed it indeed, thank you! 👍
