### ISSUE TITLE
Cooldown Count interference with Debuff Timers

### ISSUE THREAD

**Issue by AmplusNLD** [obble/modui#136]
I noticed an interference with the new Cooldown Count and the AddOn Debuff Timers.
Modui is trying to skin Debuff Timers, and I am not sure if that is on purpose since I couldn't find it in the changelogs. The issue is that is shows the timers doubled up.
If I turn off Debuff Timers, the timers don't show at all. And if I turn off Cooldown Count, it just shows Debuff Timers.

<img width="265" alt="berichten-afbeelding 972957641" src="https://cloud.githubusercontent.com/assets/25012428/22689376/0f91148a-ed31-11e6-8df3-a3df3252df77.png">

**Comment by obble** [comment]
whoops! i'll look to fixing this.

eventually i'd like to include cooldown counts on target debuffs within modui, maybe this can expedite that as a fix.

**Comment by AmplusNLD** [comment]
Cool, looks like you are already half way there.
