### ISSUE TITLE
Changing tooltip healthbar color for shamans

### ISSUE THREAD

**Issue by Violet-Vibes** [obble/modui#138]
I know they were pink in vanilla but is it possible to have the tooltip show shamans healthbar as blue instead of pink? I've been toying around and managed to get everything shaman related to blue but the tooltip hp bar

**Comment by AmplusNLD** [comment]
Are you using the latest version of modui or any other addon that does tooltips? Because shaman tooltips are blue for me.

**Comment by Violet-Vibes** [comment]
Latest version, I'm using tinytip but using the edit found at https://forum.nostalrius.org/viewtopic.php?f=63&t=41741

I'm refering to the statusbar being pink, the tooltip itself shows shamans "correctly" as blue, see picture https://i.imgur.com/sGPAvYW.jpg

**Comment by Violet-Vibes** [comment]
Okay, it was SuperInspect messing the colors up, I'll dig around in the code and see if I can change it there, having it on made the statusbar for some reason pink.
