### ISSUE TITLE
Energybar fade

### ISSUE THREAD

**Issue by roanaes** [obble/modui#151]
hello, is it possible to have the energybar without the out of combat fading or full energy fade?

i use ravage+shred combo and need to time the tick properly to get it asap and right now i have to use addon called energywatch with this ui since the energybar on modui is so unreliable when stealthed or full energy :/

otherwise great addon!

**Comment by obble** [comment]
the current version of modui doesn't fade the energy ticker out of combat or when at 100%

cheers
