### ISSUE TITLE
[Question] - Any intentions of coming back @modernist?

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#155]
So there haven't been any updates for a while nor do you reply on any of your threads on various forums anymore so I assume you just quit after the Elysium drama happened, however do you currently have any intentions of coming back or start to work on this amazing project again? And if yes then when? :)

@obble / Modernist

**Comment by obble** [comment]
i'm updating a very barebones of the ui ([here](https://github.com/obble/ladyui)) for TBC as i move to play on felmyst but have essentially stopped updating modui at this point in time. 

I'll probably add a fix for the error caused by the friends list some point soon though.

thanks, M.
