### ISSUE TITLE
Chat Being spammed.

### ISSUE THREAD

**Issue by mahlina** [obble/modui#156]
Every ability from mount to a spell is spamming
"+useaction"

it just  spam's my chat, tired modui off and its stoped, wanted to know if anyone know the solution to this problem!
Thank you in advance!

**Comment by Steffen-Hadberg-Nielsen** [comment]
Screenshots would be ideal..

But modUI isn't very fond of other UI/addons so there you have it most likely....

**Comment by obble** [comment]
this is being caused by another addon, possibly some kind of macro thing.
