### ISSUE TITLE
Adding element from Gypsy Unitframes to Playerframe

### ISSUE THREAD

**Issue by dogmax** [obble/modui#158]
Is there a way to add elements that are colored by the colorpicker? I am asking because I am using Gypsy Unitframes as well which add an element to the normal Playerframe and i want that element to get colored as well. Here is a screenshot: 

http://i.imgur.com/fF24A01.png
http://imgur.com/fF24A01

You can download the Gypsy Unitframe here: 
https://www.dropbox.com/s/p19l6ovex46kguj/Gypsy_UnitBars.zip?dl=0

**Comment by obble** [comment]
something like

```
local _, v in pairs(
    {
        Gypsy_PlayerFrameRight,
        Gypsy_PlayerFrameBottom,
        Gypsy_PartyFrame1FrameRight
    }
) do
    tinsert(MODUI_COLOURELEMENTS_FOR_UI, v)
end
```

note that you have to load this after modui and gypsy have themselves loaded

**Comment by dogmax** [comment]
I put that in a seperate lua file? Or do I put the edit in the unit,lua?

**Comment by obble** [comment]
yeah you could put it in unit.lua and it should work

you might need to wrap it in a function that checks if gypsy is loaded. something like this:

```
local gy = CreateFrame'Frame'
gy:RegisterEvent'ADDON_LOADED'
gy:SetScript('OnEvent', function()
    if arg1 == 'Gypsy_UnitBars' then
        for _, v in pairs(
            {
                Gypsy_PlayerFrameRight,
                Gypsy_PlayerFrameBottom,
                Gypsy_PartyFrame1FrameRight
            }
        ) do
            tinsert(MODUI_COLOURELEMENTS_FOR_UI, v)
        end
    end
end)
```
