### ISSUE TITLE
Buff/Debuf timers (minor bug)

### ISSUE THREAD

**Issue by minimoncho** [obble/modui#19]
Just a little bug on the buff/debuff timers in the seconds display. When a buff/debuff has only 21:03 min/sec it shows 21:3 for example.
![timers](https://cloud.githubusercontent.com/assets/18060696/14176070/6865e56e-f74f-11e5-9a52-aadc0a060843.png)

**Comment by minimoncho** [comment]
Found how to fix it in Globals/math.lua in line 16 add 02 to ('|cffffffff%d|r:|cffffffff%d|r', m, s) to look like ('|cffffffff%d|r:|cffffffff%02d|r', m, s)

**Comment by obble** [comment]
thanks, will update

**Comment by obble** [comment]
fixed in v69
