### ISSUE TITLE
BG maps flag carriers tracker

### ISSUE THREAD

**Issue by minimoncho** [obble/modui#20]
While it works properly detecting who picked up the flag, it doesn't forget it if he drops/cap it. 
![bg maps](https://cloud.githubusercontent.com/assets/18060696/14176053/5739c918-f74f-11e5-81c6-86b14313be6b.png)

**Comment by obble** [comment]
note to self: this is caused by raid members leaving/joining the battleground and the raid ids shifting to accommodate.

**Comment by obble** [comment]
this should be fixed in this latest version.
