### ISSUE TITLE
[Suggestion] Rogue energy spark always on

### ISSUE THREAD

**Issue by Red86** [obble/modui#21]
Hello,
I've been using this UI and this is my only minor issue with it. The energy spark that shows you when the next tick is going to be is immensely helpful but, it vanishes when the energy caps. In PvP situations however, it's really helpful to open on someone as close as to the next tick as possible to maximize damage and at the moment there's no such option to do so in the UI.

So, I tried to change the code in the energy.lua file. I tried to change the line "if arg1 == 'player' and p < 100 then" this, partially works. The spark won't show outright but, as soon as I lose some energy it will and, it will do so even once the energy caps to 100. 

I then tried to remove line 39-45 and this, did what I wanted, the spark was showing right from the moment I logged in without the need to hit anything. However, I noticed that in this way the spark was inaccurate, the energy tick weren't matching were the spark was, something that doesn't happen with my method outlined above. I suspect it might have something to do with: "if p == last + 20 then t = GetTime() end"

I wanted to ask if it was possible to make the spark visible (and accurate) at all times or, the best thing that can be done is to have it appear only after experiencing an energy loss?

Thanks

**Comment by obble** [comment]
energy tick will now be permanently shown as of v69.

the nature of the prediction means that the spark can only be correctly updated once energy has first been used, and this resets when entering or leaving combat. so it remains an estimate. i'll look into creating stronger prediction that takes this into account in the next few versions.
