### ISSUE TITLE
modui keypress

### ISSUE THREAD

**Issue by kev41** [obble/modui#24]
hey man. how can i contact you nowadays? like i have to create an issue to write to you.
anyway, awesome addon for vanilla the modui, but the keypress im so used to 10 years + of spells activate when key goes up, so you can change your mind if you click etc. 

is there a line in the keypress.lua i can change to make this change? i like the press animation, and deleting it makes it no press animation at all

thanks in advance. you can also contact me on kevven41@gmail.com

**Comment by kev41** [comment]
any idea for this? :)

**Comment by obble** [comment]
its something i'll look at soon ~ it should be a fairly simple process to introduce an option to toggle them.

**Comment by kev41** [comment]
@obble is there something I can change in keypress.lua meanwhile?
I see several lines where it says 'PUSHED' and 'NORMAL' can I change it to something like 'RELEASED' or it is totally something else?

thanks in advance.

**Comment by colroyds** [comment]
I would also like this. Tried playing around with keypress.lua but like the user above it would only remove the GCD animation entirely. Is this something that's still being worked on? 

Thanks for the addon.

**Comment by kev41** [comment]
I would even donate for this :)

**Comment by obble** [comment]
this fell lower down on my priority queue than some other bugs but should get around to it this week. hoping to include in the next revision of the addon :o)

**Comment by kev41** [comment]
:( this

well thanks alot for an update!

**Comment by obble** [comment]
there's a bug that meant it didn't make it this time around, i have been working on it though! stay tuned

**Comment by obble** [comment]
pleased to say this is now an option as of version 83. thanks for bearing with me!
