### ISSUE TITLE
Enhancement - Option to get "Large Healthbar" 

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#26]
If possible, it would be amazing if you could add an option to enable large healthbars like on this image http://i.imgur.com/vdobk3N.jpg (Name is outside the actual frame to make it look more clean and to give more space for status text)

The image is taken from a random google search but it linked to this UI http://www.wowinterface.com/downloads/info18074-RufioUIClassic.html
maybe you can copy some code from it if you want to implement the large healthbars

Also found this one http://www.wowinterface.com/downloads/info20444-EnhancedBlizzardUI.html

**Comment by obble** [comment]
this is originally based on [oUF Abu](http://www.wowinterface.com/downloads/info23020-oUFAbu.html). I believe I remember someone on the nostalrius forums exploring a backport or analog addon in this kind of style.

I won't be including this in the design of modui, its a layout option which other authors can look to realise if they so wish.
