### ISSUE TITLE
Status bar luminance is a bit low

### ISSUE THREAD

**Issue by ghost** [obble/modui#29]
After the texture change on the status bar in v72 (which I really like having it texture less.. feels a lot cleaner). On first glance to me.. it feels like the Health / mana bars are abit dark.. like the green/blue/yellow/red depending on ur class is sort of a more "mucky" colour compared to how it was before.. these bars should be bright and colourful.

I've had this issue before while i was messing around with nameplate backgrounds. Not sure what can be done about it.. as even with alpha set to 1.. the bar colour still seems to be reactive to its background

**Comment by obble** [comment]
i switched the hp + mana bars to the slightly lighter gradient statusbar texture i've used in my retail wow ui and i agree that it looks better for the added vibrancy:

![new statubars](http://i.pi.gy/nxgE.png)

the change in values is brought about by the greyscale tone of the statusbar texture itself ~ you can adjust this further by cracking it open in photoshop or importing your own file within the modui/statusbar/texture directory.

**Comment by ghost** [comment]
Looks much better! That makes sense, I had not actually looked at the code for the bars or what/if they were hooked up to any textures. Figured I just write and issue straight away and see what you think.

Im currently looking at nameplates, textures are a bit out of position on my end... likely another resolution / ui scale and I have some ideas regarding the issue were debuffs get shown across multiple nameplates on units with the same name. If you would like to feel free to send me an email to stevenshiers@gmail.com with you skype/steam to make it a bit easier for us to chat about things.

:)

**Comment by obble** [comment]
sure.

closing this now as its fixed in [v73](https://github.com/obble/modui/commit/11dca1ae77aed6c82bbfe8b08c6a9082f918bcfb). feel free to reopen to discuss further though
