### ISSUE TITLE
Unit Frames can't be moved with MoveAnything

### ISSUE THREAD

**Issue by ghost** [obble/modui#31]
When trying to move the unitframes with MoveAnything they stay in place and kinda bug out.

Here's the link to the addon: http://addons.us.to/addon/moveanything .

**Comment by obble** [comment]
this is probably a conflict with the movement functions for unit frames that are introduced by modui — which allows you to set their position by shift + dragging (and reset with "/reset").

i'll look into resolving the conflict, but its at a low priority.

**Comment by ghost** [comment]
The problem here is that what I'm trying to do is to resize the unit frames. I like having the UI scale really low but this makes the unit frames too small.

Maybe just include an option to resize the unit frames?

**Comment by Steffen-Hadberg-Nielsen** [comment]
Moveanything works fine for me, i also scale my unitframes up and move them. 
I first noticed after moving them with Moveanything that you could move it with just modui, I dont know how to lock them with modui tho

**Comment by ghost** [comment]
Yeah, it works good now. They were bugging out when trying to rescale and move them but seems like they are all fixed now.

**Comment by obble** [comment]
closing this since it appears to be fixed
