### ISSUE TITLE
Questie button outside the world map frame

### ISSUE THREAD

**Issue by ghost** [obble/modui#32]
The "Toggle Questie" button is outside the world map frame.

Screenshot: http://i.imgur.com/hXcw5rd.png

Addon link: https://github.com/AeroScripts/QuestieDev

**Comment by obble** [comment]
fixed in the next revision

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
