### ISSUE TITLE
Add options to the minimap clock button

### ISSUE THREAD

**Issue by ghost** [obble/modui#33]
The day/night button on the minimap which is also used to toggle the stop watch displays the time in a tooltip, but has no option to change the time to the local time/server time or the format to 12hour/24 hour.

Can you please include those options? Would be appreciated.

**Comment by obble** [comment]
added in the next revision, shift + click to switch between 12/24hr, shift + right click to switch between server + local time. these options are explained within the tooltip.

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue.
