### ISSUE TITLE
Integrate Clean_Up

### ISSUE THREAD

**Issue by ghost** [obble/modui#35]
I tried using the addon but it cannot be hooked to the bag frame. Can it be added as an option with a button near the keyring button?

Link to the addon: https://github.com/shirsig/Clean_Up

**Comment by obble** [comment]
I've been meaning to install & possibly support this addon within modui, will try it out this week.

**Comment by EffToyz** [comment]
It's more bug than feature request.

Error:  EnumerateFrames: Couldn't find 'this' in current object
AddOn: Clean_Up_GUI
File: Clean_Up_GUI.lua
Line: 111
Count: 1
--------------------------------------------------
Error:  attempt to index field `target' (a nil value)
AddOn: Clean_Up_GUI
File: Clean_Up_GUI.lua
Line: 167
Count: 1

With modui off Clean Up GUI works perfectly.

**Comment by obble** [comment]
this was an issue caused by healcomm, see [github.com/Aviana/LunaUnitFrames/issues/145](https://github.com/Aviana/LunaUnitFrames/issues/145).

the next revision will include the latest version of the library which should fix the issue.

**Comment by obble** [comment]
Clean Up GUI is now compatible with this addon
