### ISSUE TITLE
Include QuickLoot

### ISSUE THREAD

**Issue by ghost** [obble/modui#36]
Just a QoL feature, it brings the loot window under the cursor. It has no conflicts with modui and works just fine as a standalone addon, but most people have no idea about it and would be useful to have it all under modui.

Link to addon: https://wow.curseforge.com/projects/project-1148

**Comment by obble** [comment]
will look into adding this in future

**Comment by ghost** [comment]
I’m using QuickLoot with modui too, but would be great to have it built in.

**Comment by obble** [comment]
i think this can continue to be added via quickloot rather than built in, since there's no conflicts between the addons
