### ISSUE TITLE
Frame drop when bags are opened

### ISSUE THREAD

**Issue by stokbaek** [obble/modui#4]
Hello,

I am getting a massive dip in frames when I open oneBag. My FPS drops from 60 FPS to 30 FPS. This is only happening with modui and not other bag addons I have tried.

**Comment by obble** [comment]
Looking into this further — couldn't reproduce a dip in FPS but attempting to reproduce the issue across a couple of different installs

**Comment by stokbaek** [comment]
I have discovered this is only happening if I am playing on my Linux partition. This might not be something you will be able to fix and just bad emulating from wine sadly.

**Comment by obble** [comment]
unfortunate — i'm going to close this for now, but please reopen if you find a solution or have additional comments. Thanks, M.

**Comment by elraro** [comment]
I have exactly the same problem. FPS drops when open the bag
