### ISSUE TITLE
Suggestion: Make tooltip movable.

### ISSUE THREAD

**Issue by kev41** [obble/modui#41]
Really like your tooltip looks and functions, but would love to be able to move it instead of using another addon.

**Comment by ghost** [comment]
Or at least an option to attach the tooltip on the mouse cursor.

**Comment by obble** [comment]
both of these options are incoming

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
