### ISSUE TITLE
Map foglight

### ISSUE THREAD

**Issue by ghost** [obble/modui#44]
I'm sorry if this option is already there but I can't seem to find it.

Can you add a foglight toggle on the map? You can probably get some of the code from Cartographer/Modules/Foglight.lua . Here's a link to Cartographer: http://www.vanilla-addons.com/dls/cartographer/

**Comment by obble** [comment]
you can use cartographer for this if you want it ~ its not a feature i currently intend to introduce. thanks.

**Comment by mrrosh** [comment]
I actually like your map better, anyway, just found out MozzFullWorldMap who does exactly just this thing. Here's a link to the addon if anyone wanna get it: http://www.mediafire.com/file/24bjnygqyd63mkx/mozzfullworldmap.rar
