### ISSUE TITLE
 Height of nameplates

### ISSUE THREAD

**Issue by ghost** [obble/modui#45]
> Is there any way to reduce the height of nameplates as well as make them appear a bit higher above the target's head? As a melee with my camera zoomed fully out, I'm having a bit of trouble actually viewing the enemy that I'm attacking due to the nameplates (makes it hard to see which way they are facing).
(I'm thinking something along the lines of the picture shown here: http://www.wow-one.com/forum/topic/30897-its-here-a-nameplate-addon/)

https://www.reddit.com/r/LegacyAddons/comments/5dmbz6/modui_a_twist_to_the_default_ui/dab8ej9/

**Comment by obble** [comment]
reposting my reply to this request from the nost forums:

_im not sure this is possible to fix through addons, as changing the scale will make the problem worse, and direct changes to positioning are impossible with nameplates in vanilla._

_i'll look at adding an option that still looks good, but also ~ this is vanilla and i do try to keep things relatively authentic. other addons can already offer this style & functionality and the sort of sleek, textureless, slightly bland look introduced in legion._
