### ISSUE TITLE
Suggestion: Make status text react to current health

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#46]
Just like the health bar itself does - when it gets close to 50% it turns yellow, when it gets close to 0% it turns red

**Comment by obble** [comment]
this is introduced in the next revision

**Comment by Steffen-Hadberg-Nielsen** [comment]
Any ETA on when that will release? :)

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
