### ISSUE TITLE
Suggestion: Offer more useful commit messages and create tags for GitHub "releases" instead

### ISSUE THREAD

**Issue by Schaka** [obble/modui#47]
Commit messages should give an insight into what is being changed in said commit. It helps automating a changelog, also.

GitHub has a great release page, that you can publish git tags on (you can check out some of my repos). It allows you to upload a binary  and publish releases in a versioned way. It also offers a more clean and usable way to offer your addon for download, including screenshots, etc.

**Comment by obble** [comment]
agreed ~ my use of git has been extremely amateur up until now, but as I've gotten to grips with it via professional work I see there's plenty of room for improvement for developer and user understanding.

**Comment by obble** [comment]
rereading this ~ changes are documented in the comment field of a commit, there's often numerous updates pushed simultaneously (see: [example](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0)) and this allows them to be grouped without having to provide a long or ineloquent title.

in the long-term it would be nice to move into release version structure and use commits for individual changes, but for now i'll probably stick with what i have been doing, its only a daft video game mod anyway. I will re-open this ticket when I can get around to reviewing again.

the next revision will introduce a README to cover the content and offer instructions for installation and FAQs. I generally personally prefer this to the github release page style.
