### ISSUE TITLE
Bug: Tooltip gets attached to mouse when bags are opened.

### ISSUE THREAD

**Issue by kev41** [obble/modui#49]
Even with modified tooltip disabled in modui settings this happens.

https://gyazo.com/f8f79f3c2cd017af836aa92cd7046340

**Comment by obble** [comment]
this is intentional behaviour but should be disabled with the modified tooltip, will be fixed shortly

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue

**Comment by kev41** [comment]
v77 still bugged with attached to mouse when bags are opened
