### ISSUE TITLE
Stance / Heroic Strike (etc.) Outline Extremely Difficult to See

### ISSUE THREAD

**Issue by lystig12** [obble/modui#51]
As a warrior, it is extremely difficult to see which stance you're in or whether or not you have activated Heroic Strike / Cleave for your next swing. I'd really love a way to make the outline far more visible! An option within the addon would be swell.
Alternatively, you could just tell me which line(s) I have to edit in the addon's .lua files, then I can do it myself! :)

**Comment by lystig12** [comment]
Here is an example so that you know what I mean:

![example](https://cloud.githubusercontent.com/assets/23642290/20983733/ddd62eec-bcbd-11e6-987b-1cfe523f44db.PNG)

Edit: Heroic Strike is queued, and Battle Stance is active. But you don't (I don't anyway) notice at a glance.

**Comment by obble** [comment]
I've changed the colour to hopefully be a little more visible at a glance in an upcoming revision

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
