### ISSUE TITLE
Cast Bar below Player Unit Frame

### ISSUE THREAD

**Issue by ghost** [obble/modui#52]
Hi Modernist,

Love the addon. Thanks for continuing working on it for so long!

I would appreciate if you would consider incorporating the player cast bar below the player unit frame, in the same fashion the enemy cast bar is currently set up. I think it would be especially useful for people like me who has their unit frames just below the center of the screen. Also, classes that don't cast spells that often (warrior, rogue) would have their UI just a bit cleaner.

Best,
Kyre

**Comment by Cruzix** [comment]
In addition to this, i'd appreciate if you could make both castbars moveable, currently enemy castbar cannot be moved

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
