### ISSUE TITLE
Suggestion: Make a ModUI version with only basic functionality

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#54]
ModUI has a lot of nice features aside from changing the look of the unitframes, but not all of the features fall in to everyones taste, so it would be nice if you could make a version of modUI that ONLY changes the look of basic things like Player/Target/TargetofTarget/Party frames and castbar+enemy cast bar. 

This would make it much easier for people who also tend to use other addons because current ModUI sometimes seem to overwrite a lot of other addons functionality, look or placement.

**Comment by obble** [comment]
unfortunately most users would have varying ideas on what elements should or shouldn't be included in a basic version. it would also mean having to maintain two separate addons.

i won't be working on this, but i will continue to enable users to toggle elements on or off within the modui menu to a greater degree.

**Comment by Steffen-Hadberg-Nielsen** [comment]
Alright, that would do it as well! 👍
