### ISSUE TITLE
Flag and Flag Carrier Name

### ISSUE THREAD

**Issue by ghost** [obble/modui#55]
When someone picks a flag in WG, "Flag" gets mixed with their name. I assume an easy fix would be to just remove "Flag" and leave flag carrier names.

![flag-overlay](https://cloud.githubusercontent.com/assets/18236471/21105938/d16563a0-c094-11e6-8a8a-4b8399ac78b5.jpg)

**Comment by obble** [comment]
this is fixed in the next upcoming version

**Comment by ghost** [comment]
Sweet, thank you!

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
