### ISSUE TITLE
Wrong Debuff Timer on Name Plates

### ISSUE THREAD

**Issue by ghost** [obble/modui#56]
Currently talents are not taken in consideration when displaying debuff timer on name plates. Only tested Improved Gouge though. Maybe other spells display correct timers. I understand that it might be tricky to implement all talents and perhaps some set bonuses, but would be nice to have.

The Enemy Frames addon works as you can see it displays 5 seconds under the enemy unit frame.

On a side note, it would be great to have the font on name plate debuff timers more visible. Perhaps a bit bigger and yellow?

![debuff timer](https://cloud.githubusercontent.com/assets/18236471/21108867/5494cd24-c09f-11e6-8c25-7b997272be52.jpg)

**Comment by obble** [comment]
i've been looking into this. as far as i can tell — enemyframes doesnt have any system that accounts for talents on players beyond assuming the rule of "if a player is using a skill, they're probably speccing talents in it". so all gouge casts will be treated as though they have the improved gouge timer.

i've altered the data in modui to do something similar, and will be testing this week to see whether this makes timers more or less effective at keeping accurate countdowns.
