### ISSUE TITLE
Gold Counter in Bags Overlays the Tooltip

### ISSUE THREAD

**Issue by ghost** [obble/modui#57]
Should be the other way around.

![tooltip](https://cloud.githubusercontent.com/assets/18236471/21108915/8c1b08da-c09f-11e6-8730-f7c56fe24844.jpg)

**Comment by obble** [comment]
fixed in the next upcoming revision

**Comment by ghost** [comment]
Also, on a similar topic, should the inventory window be placed closer to the lower right corner? There is quite a bit of empty space. I would say that the lower right corner of the inventory window should be aligned with the lower right corner of the tooltip (when the inventory is closed).

**Comment by obble** [comment]
another thing I've added to the next version is the ability to move the bag with shift + left click drag, which should solve your issue

**Comment by obble** [comment]
closing with the release of [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) which either fixes or adds support for this issue
