### ISSUE TITLE
I want to translate modui into chinese

### ISSUE THREAD

**Issue by zhygawaine** [obble/modui#69]
But I can not find the nameplate catbar.

**Comment by obble** [comment]
a table of text that im looking to be translated can be found in the [localisation](https://github.com/obble/modui/tree/master/localisation) folder, with chinese signified as [zhCN.lua](https://github.com/obble/modui/blob/master/localisation/asia/zhCN.lua).

if you're able to offer localisation, you can download this file, add your translations, and upload it as a text gist to gist.github.com then link the URL in this ticket.

for more information and a guide for formatting the table of strings to translate, look here: http://forum.nostalrius.org/viewtopic.php?f=63&t=21880&start=840#p318688

**Comment by zhygawaine** [comment]
your addons does not seem to call localisation file.

2017年1月9日 下午6:20，"obble" <notifications@github.com>写道：
