### ISSUE TITLE
Adding a paging option as hunter

### ISSUE THREAD

**Issue by stokbaek** [obble/modui#7]
Hey,

I have been using this addon (https://github.com/Aviana/HunterPaging) that does some paging in action bars when you are in melee range.

This does not seem to work with the standard bars, but only with addons like zbar.

Would it be possible to add this option to modUI?

**Comment by obble** [comment]
i won't be adding it directly to modui — you should ask Aviana to fix that mod to work with the default bars, on a quick test it appears to be an issue with the OnUpdate structure being used.

closing this for now, cheers.
