### ISSUE TITLE
Anyway to get this compatible with mobinfo and mobhealth,? 

### ISSUE THREAD

**Issue by hvppyk** [obble/modui#71]
Edit: I actually solved the problem on my own. I turned off displaying health numbers/percentages on the modinfo config and now it only displays the health in modui font. Which looks amazing by the way. I just have a second concern. Is there anyway to move the tool tip? or any thing else about the ui? I cannot seem to find it in the /modui options

**Comment by obble** [comment]
you can move the tooltip in the "display" settings of the modui options panel.

closing this ticket for now, thanks!
