### ISSUE TITLE
Error: attempt to index local `parent' (a nil value)

### ISSUE THREAD

**Issue by lystig12** [obble/modui#73]
Hey man. I'm getting this error whenever I reload my UI / start the game.
![image](https://cloud.githubusercontent.com/assets/23642290/21555713/dec93bb4-ce1a-11e6-9ddd-40e8af29e83c.png)

**Comment by obble** [comment]
this might be an issue with your WTF cache. can you reinstall the addon, delete your WTF folder and see if this fixes the issue? you might also need to type "/rl" on first login after completing these steps to initialise your saved variables.

**Comment by lystig12** [comment]
I'm not really too keen on deleting my WTF folder. Too many settings that I don't want to redo. I fixed the problem by simply out-commenting the relevant lines in the .lua file (the lines for the tooltip function). Seems to work fine. I don't use the tooltip part of ModUI anyway. Thanks. :)
