### ISSUE TITLE
Error in unitcasting.lua

### ISSUE THREAD

**Issue by EffToyz** [obble/modui#74]
> **Error**:  attempt to perform arithmetic on field `tick' (a boolean value)
> **AddOn**: modui
> **File**: unitcasting.lua
> **Line**: 22
> **Count**: 1

This happens from time to time.

**Comment by drust6** [comment]
So far leveling everytime i faced this error was with basilisk type mobs and diemetradons in un'goro, probably there are some other types of mobs also though. The error comes each and every time when these mobs are casting.

**Comment by obble** [comment]
i think i've found the issue causing this, i'm doing some more testing this week (when i can get past the queues)

**Comment by Finrodi** [comment]
http://i.imgur.com/oZcUYhg.png

**Comment by kev41** [comment]
Yep http://imgur.com/a/yWwzX

Mob: Diemetradon

**Comment by obble** [comment]
fixed in v78
