### ISSUE TITLE
Option to make pet frame look the same as TargetofTarget frame, but reversed

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#77]
Option to make pet frame look the same as TargetofTarget frame, but reversed so the healthbar and powerbar will go under my portrait, just like ToT's healthbar and powerbar does to target portrait
![image](https://cloud.githubusercontent.com/assets/6162744/21885056/54d87efa-d8b6-11e6-86fa-1954dfc25b32.png)

**Comment by obble** [comment]
this is not planned for now.
