### ISSUE TITLE
Option to anchor enemy buffs & debuffs to above target unitframe instead of below

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#78]
Option to anchor enemy buffs & debuffs to above target unitframe instead of below
It's possible to move the enemy buff & debuff frame with the MoveAnything addon by typing these commands /move TargetFrameBuff1 and /move TargetFrameDeBuff1 however there's no way of changing its grow direction from down to up with MoveAnything, so it will just clip through the unitframe if you simply move it.

**Comment by Steffen-Hadberg-Nielsen** [comment]
Shirsig posted a link to something that might be useful to make this feature happen 
https://forum.elysium-project.org/topic/32153-need-help-to-change-enemy-debuff-position-and-growth-direction-default-unitframes/

Also, any chance you could make the enemy debuffs clickthrough, so if you accidentally hit them when trying to move the camera, u'd still be able to do so? :)

**Comment by obble** [comment]
Yeah, I've been meaning to work on adding this functionality as part of the move to insert all options available to the  unitframe in the default retail ui (i.e. support for the popular centralised unit layout).

this includes auras growing from the top of the frame as well as the option to move the target cast bar to a custom location (already introduced in the next available version).

**Comment by Steffen-Hadberg-Nielsen** [comment]
Some more relevant information regarding this request: https://www.reddit.com/r/LegacyAddons/comments/5ncrqp/looking_for_an_addonscript_to_move_the_default/dcvpvav/ (Schaka's response)

**Comment by obble** [comment]
added as of version 83.
