### ISSUE TITLE
Few incompatibilities with Questie and MobInfo2

### ISSUE THREAD

**Issue by Aradyan** [obble/modui#80]
Hi, first of all thanks for all the work you're putting on this mod ! It looks very cool and all the optionional mods are great. I would like to point out some incompatibilities with Questie and mobinfo2 which are 2 very used addons (and some suggestions).

**Mobinfo2 incompatibilities :**
 Health/mana are displayed both by modui and mobinfo2, which turned out to be unreadable. Only solution to use both addons (and use mobinfo2's uselfull tooltip) is to switch off health and mana of mobinfo2.
What could be done is to wether allow the player to not to show modui's status and therefore choose between the 2 addons (or set up an option that gives a priority to this or that addon that would overwrite the other) or give the opportunity to use mobinfo2's databse as it is the feature that doesn't work.

**Questie incompatibilities :**
- I think the problem is resolved with the last version of Questie, but these one is very bugged so I just want to report the issue. When a quest is tracked, both addons (when the Tooltip optional mod is chosen in Mobinfo2) show quest item tracker in the tooltip window.

 **Some suggestions :**
- Show available slots but minus the ammo bag's slots (option to switch on/off ?)
- Show health in percentage or real value of party's members and target's target.
- Having an option to have the writing area not above the chat but below would be great !

**Other :**
- Tooltip's luminosity (when a mob is hovered) seems to interact with the environment's brightness. When we go to a zone where the environment is dark with a cloudy weather (for instance, in the Taurens starting zone the Brambleblade Ravine) the brightness of the hovered mob's health bar become darker.
- The number of target for mobs of level  is not totaly center with the UI circle where. Too moch to the right for level 1-9, the opposite for above. That's not a big deal though

**Comment by ghost** [comment]
In Addons/Modui/libs delete mobhealth folder.

**Comment by Aradyan** [comment]
Well it does work for the mobhealth incompatibility but it still shows an error every time I connect and it's bit annoying even with improved error frame. I think "an official" option is still the better solution, thanks anyway

**Comment by obble** [comment]
i have added a check in the next version (going up today) that should mean that these libraries wont load when using mobinfo2.

questie issue seems to be resolved so no action required.

bag not counting ammo (or other specialised type) slots is a good suggestion.

chat editbox alignment option is planned

**Comment by obble** [comment]
this has been introduced in the latest version.
