### ISSUE TITLE
Enhancement: Small config tweaks.

### ISSUE THREAD

**Issue by AmplusNLD** [obble/modui#81]
Hello, first of all, thank you for working on this great addon. I have been using modui for a while now and would like to be able to edit some part I personally don't really like.

#### Chat
The first thing is the ChatFrameEditBox being on top of the chat window instead of being below. I would love to see a simple check box in the config window to have it either on top or below the chat window. I think other people would like to see this as well.

#### Status text
The next thing is the coloured status text in health and mana bars of the player and target frames. I would really like to see a checkbox just to make that text white just like in the older version of modui. The text of the health bar changing colour with the bar itself makes it sometimes hard to read as someone who is colourblind.

#### Scrolling combat text
Also the scrolling combat text, I don't really get why it scrolls on the right side of my character and sometimes on the left side without any consistency. I would like to see some more config options for that or a checkbox to make it just on the right side or in the middle of the screen, or just a checkbox to turn it off completely to be able to use the stock SCT.

#### Raidframes
What I also was wondering, why to I need to right-click on a raidframe to target it instead of left-clicking like you have to do when you try to target someone it the party frames.

#### One-bag
Lastly, I noticed some kind of bug with the one-bag option. If you have one-bag turned on and you want to open your bank. its doesn't show the bags you have on your bank and it closed the bank window if you try to open them with B or shift + B. You have to manual click the bags in your bank to let them show op.

I hope you find something useful in this feedback, keep up the good work!

-Amplus

**Comment by obble** [comment]
a lot of this is fixed in the next version, the others have been taken into account for future revisions.

raidframes should already now use left-click instead of right-click to target, make sure you're using the latest version :o)
