### ISSUE TITLE
Saved variables resetting + menu items disappearing after login

### ISSUE THREAD

**Issue by obble** [obble/modui#82]
so far unable to replicate this issue

https://forum.nostalrius.org/viewtopic.php?f=63&t=21880&start=950#p321638

https://forum.nostalrius.org/viewtopic.php?f=63&t=21880&start=950#p321629

**Comment by gashole** [comment]
Register a new cvar and reloadui to replicate this issue.

**Comment by obble** [comment]
oh wow, there's a hard limit?

![screen shot 2017-01-24 at 20 05 53](https://cloud.githubusercontent.com/assets/96432/22264625/9cbc1b1e-e270-11e6-9001-ab6b3031aa6f.png)

**Comment by kschir** [comment]
I'm having the same issue.

**Comment by obble** [comment]
managed to replicate the issue now and understand the cause behind it. hoping to solve within the next day or two.

it seems there's essentially an invisible hard-limit on the amount of saved variables (stuff that remembers whether you want your gryphons toggled on or off or whatever) you can create. This means i'll switch over to using a table of vars, which is what i should have been doing in the first place.

**Comment by kev41** [comment]
yeah this bugs out addons for me ill download older version for now

**Comment by kev41** [comment]
downloaded older version and now my Informant addon works again, dunno why it caused it to bug.

(Informant,EnhTooltip,Stubby) is one pack for sellvalue.

**Comment by obble** [comment]
this seems to have been fixed within the latest version, please re-open this ticket if any issues regarding saved variables or a freaked-out menu remain.
