### ISSUE TITLE
Bug on spell bar after traveling with a boat

### ISSUE THREAD

**Issue by johnnybgood89** [obble/modui#87]
There is a bug , where you travel with a boat and after loading screen, spell bar mess up. You need to reload

**Comment by obble** [comment]
unable to replicate this, can you make sure that you have

1. quit the game
2. updated to the latest version (currently "81")
3. removed modui files from your WTF folder

**Comment by johnnybgood89** [comment]
No Im using v 77, cuz 79 was totally broken for me. Ill try and see. Thanks
