### ISSUE TITLE
Some BUGs and suggestions 

### ISSUE THREAD

**Issue by kefirok** [obble/modui#90]
**BUGs:**

- Raid marks looks bad http://imgur.com/a/wPktu and End Cap Textures overlap spell buttons
- Scroll down button is bug (in all windows except general)  http://imgur.com/a/nEyk2
- Timestamps not working
- Scrolling Combat Text options not working
- Debuffs at enemies nameplates work bad (for example Polymorph one of enemy in crowd, also displayed on others) - (like issues#25). Can you add option to enable/disable this?

**Some suggestions:**

- Rare/elite borders on/off option (dark look better for me)
- Add addons PriceDB, AuctionLink, EquipCompare, DebuffTimers to UI
- "Reset" button to auction
- Add Atlas and AtlasLoot buttons to dark.lua
- Add local time (this implemented at pfUI)

Sorry for my bad english

**Comment by johnnybgood89** [comment]
Yeah I would like to see debuffs fixed.

**Comment by obble** [comment]
most of these are already fixed in the next version or planned.

see [ticket 25](https://github.com/obble/modui/issues/25) for a discussion on the issue with nameplate auras being shared between mobs with the same name. an option to enable or disable them on non-player mobs is a good idea though.

**Comment by kefirok** [comment]
add one more suggestion

**Comment by obble** [comment]
some of these have been implemented in v83

**Comment by obble** [comment]
oh and the scrolldown button is fixed in v83.5.

other suggestions have been noted, im going to close this for now.
