### ISSUE TITLE
Changelog file

### ISSUE THREAD

**Issue by johnnybgood89** [obble/modui#91]
Hello obble,

Can you add changelog txt file with your file for the new releases? And the version number. I cant find it and cant find what were the fixes. Thanks

**Comment by obble** [comment]
a change log can be found on the "[x] commits" page, to the top left of the code on the main page:

https://github.com/obble/modui/commits/master

clicking on each version number will offer a summary of the changes and then list all instances where code has been removed and added. here's the last version:

https://github.com/obble/modui/commit/bba026d9a21849a6f8e03beedf1424bcb0fe6357

with list of changes: 

>  ~+ druid extra mana bar now correctly accounts for shapeshifting costs
> ~+ mobhealth3 will not load if already separately loaded, or with mobinfo2
> ~- error from arrange.lua when tooltip element is disabled
> ~- obsolete code
