### ISSUE TITLE
"Reload UI" button and overlap spells by End Cap Textures

### ISSUE THREAD

**Issue by kefirok** [obble/modui#95]
Button: http://imgur.com/iPmCMri
Overlap look like this:
Blizzard: http://imgur.com/n5jgidG
modui: http://imgur.com/T4WdGfN

**Comment by obble** [comment]
[v84](https://github.com/obble/modui/commit/c0a6c5c8573e57c046bcadcb23ff38908f1a1592) fixes the offset on the reload ui warning.

the overlapping end cap textures are intentional.
