### ISSUE TITLE
Higher quality elite borders on TargetFrame

### ISSUE THREAD

**Issue by AmplusNLD** [obble/modui#96]
Since version 78. unstyled elite frames have been bugging me a bit since they don't look as smooth as they should.

I have been looking around on for some better looking frames and found [these](https://mods.curse.com/addons/wow/simplerareelite). They don't [fit](https://i.gyazo.com/b5213f5660aabc0df4b71d70fa32626a.png) perfectly yet, but that can be edited.
![EliteFrame](https://i.gyazo.com/b5213f5660aabc0df4b71d70fa32626a.png)

The idea is to show elite frames as normal frames so they can be skinned nicely with a the unskinned dragon on top.

Let me know what you think.

**Comment by obble** [comment]
I was planning to make an open call for higher quality textures to use on these frames, but got bogged down in other bug fixes for a few days. They definitely have room for improvement as it currently stands.

Any decent photoshoppers, a PNG or TGA file of a decent gold/silver dragon border for the target frame at a better quality than the ones i made ([here](https://github.com/obble/modui/blob/master/unitframe/UI-TargetingFrame-Elite.tga) and [here](https://github.com/obble/modui/blob/master/unitframe/UI-TargetingFrame-Rare-Elite.tga)) would be fantastic.

**Comment by obble** [comment]
I'll check out the versions contained in this AddOn too

**Comment by AmplusNLD** [comment]
I'll try to find some better ones and I can modify them in PS to make them fit nicely. I also like the idea of having 3 or 4 colours to show world bosses.

**Comment by AmplusNLD** [comment]
Made my own frame, what you do think?

![Frame](https://i.gyazo.com/8535336e98b543107dfe246ffcf57b57.png)

**Comment by obble** [comment]
that is _much_ better

**Comment by AmplusNLD** [comment]
Cool, will make the rare frame now, and make a pull request soon.

**Comment by AmplusNLD** [comment]
#107 made a request.

**Comment by AmplusNLD** [comment]
I was thinking of changing the TargetFrameTexture of elite targets to UI-TargetingFrame like in the last screen. So dragons don't overlap and the rest of the border is grey. But that is up to you if you like that.

**Comment by obble** [comment]
Would be best I think — i can write in the change for that

**Comment by AmplusNLD** [comment]
Okay, that would be nice.

**Comment by obble** [comment]
merged, thanks!
