### ISSUE TITLE
Random closing loot windows/option windows

### ISSUE THREAD

**Issue by johnnybgood89** [obble/modui#97]
Hello,
I have problem that my loot windows sometimes randomly closing after i click so I cant loot. Or when I want to change something in options like- that multisampling thing, the stub will expand and close. /reload fix the thing. 

I dont know if its modui related but u can check that.

**Comment by obble** [comment]
I believe this is an issue with the client rather than modui unfortunately.

also note that pop-out windows have a 3 second rule baked into them. if you move the mouse outside of the frame and leave it a second or two they'll collapse again.

**Comment by johnnybgood89** [comment]
Ok thanks for the response
