### ISSUE TITLE
Question: Keypress - Possible to do same border for downward press as upward press?

### ISSUE THREAD

**Issue by kev41** [obble/modui#99]
This highlight/border that downward press option has, but not upward
I can live with it, but just wanted to ask :)

![keypreszz](https://cloud.githubusercontent.com/assets/21115526/22443443/2e690ef0-e73f-11e6-9499-05f58a50dfe4.gif)

**Comment by obble** [comment]
sure — i'll set it so it pulses on keyup

**Comment by kev41** [comment]
You are amazing.

**Comment by obble** [comment]
added, thanks!
